# Generated by Django 4.0.2 on 2022-03-13 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='date',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AddField(
            model_name='contactform',
            name='time',
            field=models.CharField(default='', max_length=12),
        ),
    ]
