# Generated by Django 4.0.2 on 2022-03-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_main_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='fb',
            field=models.TextField(default='.'),
        ),
        migrations.AddField(
            model_name='main',
            name='tw',
            field=models.TextField(default='.'),
        ),
        migrations.AddField(
            model_name='main',
            name='yt',
            field=models.TextField(default='.'),
        ),
    ]
