# Generated by Django 4.0.2 on 2022-03-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_main_fb_alter_main_tw_alter_main_yt'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='set_name',
            field=models.TextField(default='.'),
        ),
    ]
