# Generated by Django 4.0.2 on 2022-03-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_main_set_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='set_name',
            field=models.TextField(),
        ),
    ]
