# Generated by Django 4.0.2 on 2022-03-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_main_set_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='link',
            field=models.TextField(default='.'),
        ),
        migrations.AddField(
            model_name='main',
            name='tel',
            field=models.TextField(default='.'),
        ),
    ]
