# Generated by Django 4.0.2 on 2022-03-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_main_link_main_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='main',
            name='tel',
            field=models.TextField(),
        ),
    ]
