# Generated by Django 4.0.2 on 2022-03-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_main_link_alter_main_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='fb',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='link',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='set_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='tel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='tw',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='main',
            name='yt',
            field=models.CharField(max_length=50),
        ),
    ]
