# Generated by Django 4.0.2 on 2022-03-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_main_fb_alter_main_link_alter_main_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
